export {
  mockDashboardStats,
  mockRevenueData,
  mockUserGrowthData,
  mockPopularWebtoons,
  mockAuthors,
  mockGenres,
  mockWebtoons,
  mockEpisodes,
  mockUsers,
  mockComments,
  mockMediaFiles,
  mockActivityLogs,
  mockReports,
  mockTransactions,
  mockScheduledEpisodes,
  getSharedData,
  exportToJSON,
  importFromJSON,
  downloadJSON,
  saveToLocalStorage,
  loadFromLocalStorage,
} from '@webpad/shared'

export type {
  AdminUser,
  User,
  Webtoon,
  Episode,
  Author,
  Genre,
  Comment,
  DashboardStats,
  RevenueData,
  UserGrowthData,
  PopularWebtoon,
  Notification,
  MediaFile,
  ActivityLog,
  Report,
  Transaction,
  ScheduledEpisode,
  SharedData,
} from '@webpad/shared'
